//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurProjectEntities : DbContext
    {
        public OurProjectEntities()
            : base("name=OurProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<joinedFile> joinedFile { get; set; }
        public virtual DbSet<questionOrAnswer> questionOrAnswer { get; set; }
        public virtual DbSet<subjects> subjects { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
